modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="addendum"
version="0.1.0"
displayName="Addendum"
logoFile="examplemod.png"
credits="Evtema3"
authors="cleverpanda714, EltrutLikes"
description='''
Adding new blocks to fit your ender palette!
'''
[[dependencies.addendum]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[2.0.1,)"
    ordering="AFTER"
    side="BOTH"
    