modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPL 2.1"
issueTrackerURL="https://github.com/EltrutLikes/Addendum/issues"
[[mods]]
modId="addendum"
version="1.2.1"
displayName="Addendum"
logoFile="examplemod.png"
credits="Evtema3"
authors="cleverpanda714, EltrutLikes"
description='''
Adding new blocks to fit your ender palette!
'''
[[dependencies.addendum]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
    