modLoader="javafml"
loaderVersion="[34,)"
license="GNU LGPL 2.1"
issueTrackerURL="https://github.com/Eltrut-Co/Addendum/issues"
[[mods]]
modId="addendum"
version="1.3.0"
displayName="Addendum"
logoFile="addendum.png"
credits="Evtema3, cleverpanda714, EltrutLikes"
authors="Elrut & Co."
description='''
Adding new blocks to fit your ender palette!
'''

[[dependencies.addendum]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.addendum]]
    modId="differentiate"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="AFTER"
    side="BOTH"